# Generated by Django 2.1.5 on 2019-02-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
        ('catalog', '0003_auto_20190214_1846'),
    ]

    operations = [
    ]
