# Generated by Django 2.1.5 on 2019-03-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='year',
        ),
    ]
